Add details for mutable and structured objects
CloudCannon/platform-documentation pull request #68
Opened 2023-05-11 09:10 UTC by rphillips-cc

2023-05-11 09:23 UTC, bglw commented on articles/editing-objects-in-your-data.mdx
> +Object inputs represent object data within the Data Editor. They are ideal for grouping related inputs, and hiding complicated or infrequently edited data.
```suggestion
Object inputs represent object data within the Data Editor. They are ideal for grouping related inputs, or hiding complicated or infrequently edited data.
```

2023-08-08 01:48 UTC, rycoll requested changes
I think `groups[*].description` should be `groups[*].comment`?

2023-08-08 01:48 UTC, rycoll commented on articles/editing-objects-in-your-data.mdx
> +          description: Values for search engines to read
```suggestion
          comment: Values for search engines to read
```

2023-08-08 01:48 UTC, rycoll commented on articles/editing-objects-in-your-data.mdx
> +  <comp.DataReferenceRow label="groups[*].description" type_markdown="text">
```suggestion
  <comp.DataReferenceRow label="groups[*].comment" type_markdown="text">
```

2023-08-08 01:56 UTC, rycoll approved these changes

2023-08-08 01:59 UTC, rphillips-cc commented on articles/editing-objects-in-your-data.mdx
> +          description: Values for search engines to read
It's `description` here.

2023-08-08 03:44 UTC, merged